#!/usr/bin/env bats

setup() {
  REPO_ROOT="$(cd "${BATS_TEST_DIRNAME}/../../.." && pwd)"
  SCRIPT="$REPO_ROOT/linux/wsl/dns-single-request.sh"
  WORK="$(mktemp -d)"
  mkdir -p "$WORK/etc" "$WORK/mnt"
  export WSL_CONF="$WORK/etc/wsl.conf"
  export RESOLV_CONF="$WORK/etc/resolv.conf"
  export WSL_DISTRO_NAME=test
  printf '%s\n' \
    '# This file was automatically generated by WSL.' \
    'nameserver 10.255.255.254' \
    'search Home' >"$WORK/mnt/resolv.conf"
  # WSL makes /etc/resolv.conf a symlink; mirror that.
  ln -s "$WORK/mnt/resolv.conf" "$RESOLV_CONF"
  printf '%s\n' '[boot]' 'systemd=true' >"$WSL_CONF"
}

teardown() {
  rm -rf "${WORK:-}"
}

@test "check fails before apply" {
  run bash "$SCRIPT" --check
  [ "$status" -eq 1 ]
}

@test "apply writes single-request and keeps nameserver and search" {
  run bash "$SCRIPT"
  [ "$status" -eq 0 ]
  [ ! -L "$RESOLV_CONF" ]
  grep -qx 'nameserver 10.255.255.254' "$RESOLV_CONF"
  grep -qx 'search Home' "$RESOLV_CONF"
  grep -qx 'options single-request' "$RESOLV_CONF"
  ! grep -q '^#' "$RESOLV_CONF"
}

@test "apply adds a network section and keeps the boot section" {
  bash "$SCRIPT"
  grep -qx '\[boot\]' "$WSL_CONF"
  grep -qx 'systemd=true' "$WSL_CONF"
  grep -qx '\[network\]' "$WSL_CONF"
  grep -qx 'generateResolvConf = false' "$WSL_CONF"
}

@test "apply backs up the symlink itself" {
  bash "$SCRIPT"
  [ -L "$RESOLV_CONF.pre-single-request" ]
  [ "$(readlink "$RESOLV_CONF.pre-single-request")" = "$WORK/mnt/resolv.conf" ]
}

@test "check passes after apply, and a second apply changes nothing" {
  bash "$SCRIPT"
  run bash "$SCRIPT" --check
  [ "$status" -eq 0 ]
  before="$(cat "$RESOLV_CONF" "$WSL_CONF")"
  run bash "$SCRIPT"
  [ "$status" -eq 0 ]
  [[ "$output" == *"already in place"* ]]
  [ "$(cat "$RESOLV_CONF" "$WSL_CONF")" = "$before" ]
}

@test "an existing network key is replaced, not duplicated" {
  printf '%s\n' '[network]' 'generateResolvConf = true' 'hostname = box' >"$WSL_CONF"
  bash "$SCRIPT"
  [ "$(grep -ci 'generateresolvconf' "$WSL_CONF")" -eq 1 ]
  grep -qx 'generateResolvConf = false' "$WSL_CONF"
  grep -qx 'hostname = box' "$WSL_CONF"
}

@test "existing options are kept alongside single-request" {
  rm "$RESOLV_CONF"
  printf '%s\n' 'nameserver 10.255.255.254' 'options edns0 timeout:2' >"$RESOLV_CONF"
  bash "$SCRIPT"
  grep -qx 'options edns0 timeout:2 single-request' "$RESOLV_CONF"
}

@test "revert restores the symlink and re-enables generation" {
  bash "$SCRIPT"
  run bash "$SCRIPT" --revert
  [ "$status" -eq 0 ]
  [ -L "$RESOLV_CONF" ]
  [ "$(readlink "$RESOLV_CONF")" = "$WORK/mnt/resolv.conf" ]
  [ ! -e "$RESOLV_CONF.pre-single-request" ]
  grep -qx 'generateResolvConf = true' "$WSL_CONF"
}

@test "apply refuses outside WSL" {
  unset WSL_DISTRO_NAME
  [ ! -e /proc/sys/fs/binfmt_misc/WSLInterop ] || skip "running under WSL"
  run bash "$SCRIPT"
  [ "$status" -eq 2 ]
}
